### ISSUE TITLE
Fetch siteinfo failed

### ISSUE THREAD

**Issue by ZabeMath** [Krinkle/mw-tool-orphantalk#8]
Going to https://orphantalk.toolforge.org/?wikidb=dewiki_p results in following error.

```
Fetch siteinfo failed
#0 /data/project/orphantalk/src/mw-tool-orphantalk/vendor/krinkle/toollabs-base/src/Wiki.php(147): Wiki->getSiteInfo('namespaces')
#1 /data/project/orphantalk/src/mw-tool-orphantalk/class.php(346): Wiki->getNamespaces()
#2 /data/project/orphantalk/src/mw-tool-orphantalk/class.php(53): OrphanTalk->getNamespaces('dewiki')
#3 /data/project/orphantalk/src/mw-tool-orphantalk/class.php(34): OrphanTalk->showForm()
#4 /data/project/orphantalk/src/mw-tool-orphantalk/vendor/krinkle/toollabs-base/src/KrToolBaseClass.php(55): OrphanTalk->show()
#5 /data/project/orphantalk/src/mw-tool-orphantalk/public_html/index.php(42): KrToolBaseClass->run()
#6 {main}
```

**Comment by Krinkle** [comment]
Confirmed. Thanks. I'm looking into it.
